import { Box } from "@chakra-ui/react";
import { StyledLink } from "rakkasjs";
import { FC } from "react";

const DocsPage: FC = () => (
    <main>
        TODO sorry, in the meantime there is
        <Box
            as={StyledLink}
            href="https://paka.dev/npm/openapi-zod-client"
            rel="external"
            target="_blank"
            ml="0.25"
            px="2"
            py="1"
            borderRadius="md"
            _hover={{ backgroundColor: "bg-darker" }}
        >
            this autogenerated documentation
        </Box>
    </main>
);

export default DocsPage;
