import { defineProperties } from "@vanilla-extract/sprinkles";
import { theme } from "./vars.css";

const absPos = ["auto", 0, "0", "-50%", "0%", "50%", "100%"] as const;
const size = ["auto", "0", "0%", "25%", "50%", "75%", "100%", "100vh", "100vw"] as const;
const flexAlign = ["stretch", "flex-start", "center", "flex-end", "space-around", "space-between"] as const;

export const baseProperties = defineProperties({
    conditions: {
        default: {},
        focus: { selector: "&:focus" },
        hover: { selector: "&:hover" },
    },
    defaultCondition: "default",
    properties: {
        fontFamily: theme.typography.fonts,
        fontSize: theme.typography.fontSizes,
        fontWeight: theme.typography.fontWeights,
        zIndex: theme.zIndices,
        boxShadow: theme.shadows,
        textShadow: theme.shadows,
        opacity: {
            "0": "0",
            disabled: "var(--vtmn-opacity_disabled-state)",
            "0.6": "0.6",
            "1": "1",
        },
        position: ["absolute", "relative", "fixed", "sticky"],
        display: ["none", "flex", "inline-flex", "block", "inline"],
        flexDirection: ["row", "column"],
        flexShrink: [0, 1] as const,
        flexGrow: [0, 1] as const,
        flex: [0, 1] as const,
        flexWrap: ["wrap", "nowrap", "revert", "wrap-reverse"],
        justifyContent: flexAlign,
        justifySelf: flexAlign,
        alignItems: flexAlign,
        alignSelf: flexAlign,
        top: absPos,
        bottom: absPos,
        left: absPos,
        right: absPos,
        inset: absPos,
        width: size,
        minWidth: size,
        maxWidth: size,
        height: size,
        minHeight: size,
        maxHeight: size,
        textAlign: ["inherit", "left", "center", "right"],
        textTransform: ["inherit", "uppercase", "lowercase", "capitalize", "none"],
        cursor: ["inherit", "pointer", "not-allowed", "initial", "wait"],
        pointerEvents: ["inherit", "all", "none"],
        userSelect: ["inherit", "none", "text", "all"],
        whiteSpace: ["nowrap", "unset"],
        overflow: ["auto", "hidden", "scroll", "visible"],
    },
    // Inspired from https://chakra-ui.com/docs/features/style-props
    shorthands: {
        d: ["display"],
        pos: ["position"],
        t: ["top"],
        b: ["bottom"],
        l: ["left"],
        r: ["right"],
        boxSize: ["width", "height"],
        w: ["width"],
        maxW: ["maxWidth"],
        h: ["height"],
        placeItems: ["justifyContent", "alignItems"],
        ta: ["textAlign"],
        tt: ["textTransform"],
        fs: ["fontSize"],
        fw: ["fontWeight"],
    },
});
